using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AngularAPIGenerate.Lib
{
    public class Constants
    {
        public const string SQL_CHILDREN = "WITH vwTableDependancy AS ( "
                                            + "      SELECT  "
                                            + "            tables.object_id Dependant , NULL Parent "
                                            + "      FROM  "
                                            + "      sys.tables "
                                            + "      LEFT OUTER JOIN "
                                            + "          sys.foreign_keys "
                                            + "      ON "
                                            + "          foreign_keys.parent_object_id = tables.object_id "
                                            + "      WHERE "
                                            + "          foreign_keys.parent_object_id IS NULL "
                                            + "      UNION "
                                            + "      SELECT  "
                                            + "          parent_object_id Dependant, referenced_object_id Parent "
                                            + "      FROM  "
                                            + "          sys.foreign_keys "
                                            + "  ) "
                                            + "  , vwTableHierarchy AS ( "
                                            + "      SELECT Dependant,Parent, 0 lvl FROM vwTableDependancy WHERE Parent IS NULL "
                                            + "      UNION ALL "
                                            + "      SELECT  "
                                            + "          vwTableDependancy.Dependant,vwTableDependancy.Parent , lvl+1 "
                                            + "      FROM  "
                                            + "          vwTableDependancy  "
                                            + "      INNER JOIN "
                                            + "          vwTableHierarchy "
                                            + "      ON "
                                            + "          vwTableDependancy.Parent = vwTableHierarchy.Dependant "
                                            + "  ) "
                                            + "  SELECT  "
                                            + "       OBJECT_NAME(Dependant) Dependant "
                                            + "      ,OBJECT_NAME(Parent) Parent "
                                            + "      , lvl   "
                                            + "  FROM  "
                                            + "      vwTableHierarchy "
                                            + "		where OBJECT_NAME(Parent) = '{0}' "
                                            + "  ORDER BY  "
                                            + "      lvl ASC "
                                            + "  OPTION(MAXRECURSION 0) ";
        public const string SQL_PARENT = "WITH vwTableDependancy AS ( "
                                            + "      SELECT  "
                                            + "            tables.object_id Dependant , NULL Parent "
                                            + "      FROM  "
                                            + "      sys.tables "
                                            + "      LEFT OUTER JOIN "
                                            + "          sys.foreign_keys "
                                            + "      ON "
                                            + "          foreign_keys.parent_object_id = tables.object_id "
                                            + "      WHERE "
                                            + "          foreign_keys.parent_object_id IS NULL "
                                            + "      UNION "
                                            + "      SELECT  "
                                            + "          parent_object_id Dependant, referenced_object_id Parent "
                                            + "      FROM  "
                                            + "          sys.foreign_keys "
                                            + "  ) "
                                            + "  , vwTableHierarchy AS ( "
                                            + "      SELECT Dependant,Parent, 0 lvl FROM vwTableDependancy WHERE Parent IS NULL "
                                            + "      UNION ALL "
                                            + "      SELECT  "
                                            + "          vwTableDependancy.Dependant,vwTableDependancy.Parent , lvl+1 "
                                            + "      FROM  "
                                            + "          vwTableDependancy  "
                                            + "      INNER JOIN "
                                            + "          vwTableHierarchy "
                                            + "      ON "
                                            + "          vwTableDependancy.Parent = vwTableHierarchy.Dependant "
                                            + "  ) "
                                            + "  SELECT  "
                                            + "       OBJECT_NAME(Dependant) Dependant "
                                            + "      ,OBJECT_NAME(Parent) Parent "
                                            + "      , lvl   "
                                            + "  FROM  "
                                            + "      vwTableHierarchy "
                                            + "		where OBJECT_NAME(Dependant) = '{0}' "
                                            + "  ORDER BY  "
                                            + "      lvl ASC "
                                            + "  OPTION(MAXRECURSION 0) ";
    }
}
